config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#about'
  resources :responses
  resources :quizzes
  resources :sounds
  resources :groups
  resources :users do
    member do
      get 'quiz_history'
      get 'open_join_group'
      post 'join_group'
    end
  end
  match '/login', to: 'sessions#new', via: :get, :as => 'login'
  match '/login/create', to: 'sessions#create', via: :post, :as => 'sessions'
  match '/about', to: 'pages#about', via: :get, :as => 'about'
  match '/logout', to: 'sessions#destroy', via: :delete, :as => 'logout'
  get 'data/audio/:filename', to: 'sounds#audio', as: 'audio'
end

app/models/sound.rb
class Sound < ActiveRecord::Base
  has_many :responses
  has_and_belongs_to_many :quizzes, join_table: "quiz_sounds"

  def self.get_sound(grbas_letter, difficulty)
    str = grbas_letter + "_rating"
    Sound.where("#{str} = ?", difficulty).sample
  end

  def find_score (grbas_letter)
    case grbas_letter
    when "g"
      self.g_rating
    when "r"
      self.r_rating
    when "b"
      self.b_rating
    when "a"
      self.a_rating
    when "s"
      self.s_rating
    else
      nil
    end
  end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  before_action :set_sound, only: [:show, :edit, :update, :destroy]
  before_action :set_current_user

  # GET /sounds
  # GET /sounds.json
  def index
    @sounds = Sound.all
  end

  # GET /sounds/1
  # GET /sounds/1.json
  def show
  end

  # GET /sounds/new
  def new
    @sound = Sound.new
  end

  # GET /sounds/1/edit
  def edit
  end

  # POST /sounds
  # POST /sounds.json
  def create
    @sound = Sound.new(sound_params)

    respond_to do |format|
      if @sound.save
        format.html { redirect_to @sound, notice: 'Sound was successfully created.' }
        format.json { render :show, status: :created, location: @sound }
      else
        format.html { render :new }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sounds/1
  # PATCH/PUT /sounds/1.json
  def update
    respond_to do |format|
      if @sound.update(sound_params)
        format.html { redirect_to @sound, notice: 'Sound was successfully updated.' }
        format.json { render :show, status: :ok, location: @sound }
      else
        format.html { render :edit }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sounds/1
  # DELETE /sounds/1.json
  def destroy
    @sound.destroy
    respond_to do |format|
      format.html { redirect_to sounds_url, notice: 'Sound was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def audio
    path = Rails.root.join('public', 'data', 'audio', params[:filename])
    send_file path, type: 'audio/wav', disposition: 'inline'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sound
      @sound = Sound.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sound_params
      params.fetch(:sound, {})
    end
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/views/sounds/_form.html.erb
<%= form_for(@sound) do |f| %>
  <% if @sound.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sound.errors.count, "error") %> prohibited this sound from being saved:</h2>

      <ul>
      <% @sound.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sounds/edit.html.erb
<h1>Editing Sound</h1>

<%= render 'form' %>

<%= link_to 'Show', @sound %> |
<%= link_to 'Back', sounds_path %>

app/views/sounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sounds</h1>

<style>
    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    .sound-actions {
        display: flex;
        gap: 8px;
    }

    .play-sound {
        cursor: pointer;
        color: blue;
        text-decoration: underline;
    }

    .audio-player {
        margin-left: 10px;
    }
</style>

<table>
  <thead>
  <tr>
    <th>File Name</th>
    <th>Score Explanation</th>
    <th>GRBAS Scores</th>
    <th>Audio Path</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @sounds.each do |sound| %>
    <tr>
      <td><%= sound.db_file_name %></td>
      <td><%= sound.score_explanation %></td>
      <td>
        G: <%= sound.g_rating %> |
        R: <%= sound.r_rating %> |
        B: <%= sound.b_rating %> |
        A: <%= sound.a_rating %> |
        S: <%= sound.s_rating %>
      </td>
      <td><%= sound.audio_file_path %></td>
      <td class="sound-actions">
        <%= link_to 'Show', sound %>
        <%= link_to 'Edit', edit_sound_path(sound) %>
        <%= link_to 'Destroy', sound, method: :delete, data: { confirm: 'Are you sure?' } %>
        <span class="play-sound" data-audio-path="<%= sound.audio_file_path %>">Play</span>
        <audio class="audio-player" controls>
          <source src="<%= sound.audio_file_path %>" type="audio/wav">
          Your browser does not support the audio element.
        </audio>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const playButtons = document.querySelectorAll('.play-sound');
        const audioPlayers = document.querySelectorAll('.audio-player');

        playButtons.forEach(function (button, index) {
            button.addEventListener('click', function (event) {
                event.preventDefault();
                const audioPath = button.getAttribute('data-audio-path');
                audioPlayers[index].src = audioPath;
                audioPlayers[index].play();
            });
        });
    });
</script>


<br>

<%= link_to 'New Sound', new_sound_path %>

app/views/sounds/new.html.erb
<h1>New Sound</h1>

<%= render 'form' %>

<%= link_to 'Back', sounds_path %>

app/views/sounds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sound_path(@sound) %> |
<%= link_to 'Back', sounds_path %>